import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getPlaceRepository } from '../src/lib/places/static-repository';
import { toPlaceSummary } from '../src/lib/places/types';
import type { CityCards, CityShard, PlaceExtra } from '../src/lib/places/shard';

/**
 * Splits the catalogue into one file per city under `public/data/places/`.
 *
 * Why per city and not per city-and-intent: measured, both ways. Splitting by intent
 * as well produces 45 files totalling 401 KB gzipped instead of 9 files totalling
 * 200 KB, and buys almost nothing where it would matter most — "hẹn hò" already
 * draws on 1,182 of TP.HCM's 1,247 places, so its shard is the city anyway. One file
 * per city also means the browser caches a city once and every later intent, plus
 * the itinerary page, is answered with no network at all.
 *
 * The files are generated, not committed. The manifest beside them *is* committed,
 * because the app imports it to know each shard's hash without a second round trip,
 * and because its diff is an honest record of when the data actually changed.
 */

const OUT_DIR = join(process.cwd(), 'public', 'data', 'places');
const MANIFEST_PATH = join(process.cwd(), 'src', 'lib', 'places', 'shard-manifest.ts');

/** Eight hex characters: enough that an accidental collision is not a real risk here. */
function hashOf(payload: string): string {
  return createHash('sha256').update(payload).digest('hex').slice(0, 8);
}

type Entry = { cityId: string; hash: string; cardsHash: string; placeCount: number };

function renderManifest(entries: readonly Entry[]): string {
  const rows = entries
    .map(
      ({ cityId, hash, cardsHash, placeCount }) =>
        `  '${cityId}': { hash: '${hash}', cardsHash: '${cardsHash}', placeCount: ${placeCount} },`,
    )
    .join('\n');

  return `// Generated by \`pnpm data:shard\`. Do not edit by hand.
//
// Committed on purpose: the client needs each shard's hash to decide whether its
// cached copy is still current, and fetching a manifest first would add a round trip
// to the very thing this exists to make fast.
import type { ShardManifest } from './shard';

export const SHARD_MANIFEST: ShardManifest = {
${rows}
};
`;
}

async function main() {
  const check = process.argv.includes('--check');

  const repo = getPlaceRepository();
  const cities = await repo.listCities();

  const entries: Entry[] = [];
  const files: { path: string; body: string }[] = [];

  for (const city of cities) {
    const places = await repo.listPlaces({ cityId: city.id });
    const summaries = places.map(toPlaceSummary);

    // Only districts that can actually answer. Offering one with no places is a
    // guaranteed dead end, and the wizard would otherwise have to work this out
    // again on every render.
    const withPlaces = new Set(summaries.map((place) => place.districtId));
    const districts = city.districts.filter((district) => withPlaces.has(district.id));

    // Hashed before `hash` is added, so the field cannot feed into its own value.
    const contents = { cityId: city.id, districts, places: summaries };
    const hash = hashOf(JSON.stringify(contents));
    const shard: CityShard = { ...contents, hash };

    // Address and editorial note, for the itinerary page only. Same order as the
    // shard, so the two files compress against similar neighbours.
    const extras: PlaceExtra[] = places.map((place) => ({
      slug: place.slug,
      address: place.location.address,
      ...(place.editorialNote === undefined ? {} : { note: place.editorialNote }),
      ...(place.location.googleMapsPlaceId === undefined
        ? {}
        : { mapsPlaceId: place.location.googleMapsPlaceId }),
    }));
    const cardsContents = { cityId: city.id, extras };
    const cardsHash = hashOf(JSON.stringify(cardsContents));
    const cards: CityCards = { ...cardsContents, hash: cardsHash };

    entries.push({ cityId: city.id, hash, cardsHash, placeCount: summaries.length });
    files.push({ path: join(OUT_DIR, `${city.id}.json`), body: JSON.stringify(shard) });
    files.push({ path: join(OUT_DIR, `${city.id}.cards.json`), body: JSON.stringify(cards) });
  }

  const manifest = renderManifest(entries);

  if (check) {
    const current = await readFile(MANIFEST_PATH, 'utf8').catch(() => '');
    if (current !== manifest) {
      throw new Error(
        'shard-manifest.ts không khớp với dữ liệu trong data/. Chạy `pnpm data:shard` rồi commit lại.',
      );
    }
    console.log(`✓ shard manifest khớp (${entries.length} thành phố)`);
    return;
  }

  // Cleared rather than merged: a city removed from data/ must not leave a stale
  // shard behind that the manifest no longer vouches for.
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  await Promise.all(files.map(({ path, body }) => writeFile(path, body, 'utf8')));
  await writeFile(MANIFEST_PATH, manifest, 'utf8');

  const total = entries.reduce((sum, entry) => sum + entry.placeCount, 0);
  for (const { cityId, hash, placeCount } of entries) {
    console.log(`  ${cityId.padEnd(14)} ${String(placeCount).padStart(5)} địa điểm  ${hash}`);
  }
  console.log(`✓ ${entries.length} shard, ${total} địa điểm → public/data/places/`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
