// Generated by `pnpm data:shard`. Do not edit by hand.
//
// Committed on purpose: the client needs each shard's hash to decide whether its
// cached copy is still current, and fetching a manifest first would add a round trip
// to the very thing this exists to make fast.
import type { ShardManifest } from './shard';

export const SHARD_MANIFEST: ShardManifest = {
  'ho-chi-minh': { hash: '53082fe7', cardsHash: '597a5d0c', placeCount: 1245 },
  'ha-noi': { hash: '41cd0357', cardsHash: '2eb98d27', placeCount: 1154 },
  'da-nang': { hash: 'eb5d4cd2', cardsHash: '3697b6f2', placeCount: 400 },
  'da-lat': { hash: 'da86a33f', cardsHash: '1092d2dd', placeCount: 147 },
  'nha-trang': { hash: '3eee943a', cardsHash: '05a12a17', placeCount: 250 },
  'can-tho': { hash: 'cd0adb5f', cardsHash: 'c042d944', placeCount: 179 },
  'hue': { hash: 'df204280', cardsHash: '68a4e90e', placeCount: 171 },
  'hai-phong': { hash: '7ec57c69', cardsHash: '4212cbc2', placeCount: 389 },
  'vung-tau': { hash: 'dbd82700', cardsHash: '8d88df62', placeCount: 247 },
};
