// Generated by `pnpm data:shard`. Do not edit by hand.
//
// Committed on purpose: the client needs each shard's hash to decide whether its
// cached copy is still current, and fetching a manifest first would add a round trip
// to the very thing this exists to make fast.
import type { ShardManifest } from './shard';

export const SHARD_MANIFEST: ShardManifest = {
  'ho-chi-minh': { hash: 'a5a84350', cardsHash: 'b4bda3b3', placeCount: 1353 },
  'ha-noi': { hash: 'a6a01e87', cardsHash: '2ac1e2a0', placeCount: 1233 },
  'da-nang': { hash: 'f3d40a9d', cardsHash: '5f17d023', placeCount: 512 },
  'da-lat': { hash: '4d87d8e5', cardsHash: '4ad41bd4', placeCount: 264 },
  'nha-trang': { hash: '8367a0bd', cardsHash: '0ddc2756', placeCount: 358 },
  'can-tho': { hash: '077fbff6', cardsHash: '2344f683', placeCount: 280 },
  'hue': { hash: 'be811d0b', cardsHash: 'be6ab9c8', placeCount: 281 },
  'hai-phong': { hash: 'e223f11c', cardsHash: '67d78a83', placeCount: 463 },
  'vung-tau': { hash: '75d489a5', cardsHash: '5d60c9ad', placeCount: 339 },
};
