// Generated by `pnpm data:shard`. Do not edit by hand.
//
// Committed on purpose: the client needs each shard's hash to decide whether its
// cached copy is still current, and fetching a manifest first would add a round trip
// to the very thing this exists to make fast.
import type { ShardManifest } from './shard';

export const SHARD_MANIFEST: ShardManifest = {
  'ho-chi-minh': { hash: 'e8af11f1', cardsHash: '74975137', placeCount: 1306 },
  'ha-noi': { hash: 'a25c93a5', cardsHash: '208a3e38', placeCount: 1206 },
  'da-nang': { hash: 'ac952b49', cardsHash: '389640e2', placeCount: 479 },
  'da-lat': { hash: '525aa029', cardsHash: '3ea069e9', placeCount: 237 },
  'nha-trang': { hash: '1a4cbcc0', cardsHash: '4ce2e37a', placeCount: 331 },
  'can-tho': { hash: '3922fb12', cardsHash: '629e6716', placeCount: 258 },
  'hue': { hash: 'ce6d38d0', cardsHash: '3838a37e', placeCount: 261 },
  'hai-phong': { hash: 'e43345e4', cardsHash: '50d8c42b', placeCount: 443 },
  'vung-tau': { hash: 'b266e93f', cardsHash: '1798102d', placeCount: 321 },
};
